### ISSUE TITLE
Too rapid firing causes crash

### ISSUE THREAD

**Issue by andreavs** [CINPLA/neuronify#116]
Seemingly, if two firing animations overlap, the engine crashes. Reproducible by setting speed to max and using a poisson or rythm generator with max rate.

**Comment by dragly** [comment]
Appears to be caused by the particle Emitter on CurrentSynapse. Perhaps this doesn't handle the large firing rate? Commenting out the emitter.burst(1) in this file fixes the issue, but that also removes the visual signals traveling along the synapses.

Suggestion for hack/fix: Don't call emitter.burst(1) so often. Check the time since last call. If it is less than, say, 100 ms, just skip.

**Comment by dragly** [comment]
Emitter replaced with items that move along the synapse. Might cost a bit more in terms of performance, but way more stable.
